#!/bin/bash

##############################
# Convert audio file to m4a 
# - Accepts a list of files
##############################

OIFS="$IFS"
IFS=$'\n'
for i in $@; 
do

    SOURCE_FILE=$i
    fullname=$(basename "$i")
    extension="${fullname##*.}"
    NEW_NAME="${SOURCE_FILE%.*}"

    ffmpeg -i "$SOURCE_FILE" -c:a aac -b:a 256k "${NEW_NAME}.m4a"

done;
IFS="$OIFS"

